# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Awesome' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'KakaoSDK'
pod 'FSCalendar'

  # Pods for Awesome


  target 'AwesomeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AwesomeUITests' do
    # Pods for testing
  end

end
